"""
The Compadre Toolkit for Python contains a GMLS_Module
which provides the ability to initialize and finalize 
Kokkos, a GMLS_Python class which manages constructing 
a GMLS class, managing neighbors, and applying the 
stencils generated by a particular reconstruction to 
data.
"""
from .GMLS_Module import *
from .compadre_py_util import *
name = "compadre"
